version: 2
jobs:

  build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate AMI
          command: packer validate \
          -var "aws_access_key=${aws_access_key}" \
          -var "aws_secret_key=${aws_secret_key}" \
          -var "aws_region=${aws_region}" -var "source_ami=${source_ami}" \
          -var "ssh_username=${ssh_username}" \
          -var "ami_users=${ami_users}" \
          ubuntu-ami.json
      - run:
          name: Build AMI
          command: |
            packer build \
          -var "aws_access_key=${aws_access_key}" \
          -var "aws_secret_key=${aws_secret_key}" \
          -var "aws_region=${aws_region}" -var "source_ami=${source_ami}" \
          -var "ssh_username=${ssh_username}" \
          -var "ami_users=${ami_users}" \
          ubuntu-ami.json

workflows:
  version: 2

  build_deploy:
    jobs:
      - build-base:
          filters:
            branches:
              only: master